{
  "openapi": "3.0.0",
  "servers": [
    {
      "url": "https://openapi.investec.com",
      "description": "Production environment",
      "variables": {}
    },
    {
      "url": "https://openapisandbox.investec.com",
      "description": "Sandbox environment",
      "variables": {}
    }
  ],
  "info": {
    "version": "1.0.0",
    "title": "SA PB Account Information",
    "description": "# Introduction\nThe Investec Private Banking API is a set of programmatic endpoints that can access Private Bank personal and business banking accounts. This API allows you to access the following:\n- Accounts\n- Balances\n- Transactions\n- Beneficiaries\n- Beneficiary Payments\n- Account Transfers\n- Documents\n\nThere are many possible use cases for the Account Information API: from extracting the data to aggregate it with financial data from other banking institutions to p[...]",
    "termsOfService": "https://developer.investec.com/za/terms-of-use",
    "contact": {
      "name": "Investec API"
    },
    "license": {
      "name": "Investec API",
      "url": "https://developer.investec.com/za/terms-of-use"
    }
  },
  "tags": [
    {
      "name": "Account information",
      "description": "Get data in context of an account. This includes balances and transaction history"
    },
    {
      "name": "Inter account transfers",
      "description": "Transfer funds to one or multiple accounts."
    },
    {
      "name": "Beneficiaries and Beneficiary payments",
      "description": "Pay funds to one or multiple beneficiaries. This includes payments requiring authorisation."
    },
    {
      "name": "Documents",
      "description": "List and retrieve documents."
    }
  ],
  "paths": {
    "/za/pb/v1/accounts": {
      "get": {
        "summary": "Get Accounts",
        "description": "Get a list of accounts with metadata regarding the account like Account name, Account type \n and the profile it is associated to",
        "operationId": "accounts",
        "tags": [
          "Account information"
        ],
        "security": [
          {
            "Oauth2": [
              "accounts"
            ]
          },
          {
            "Oauth2-Sandbox": [
              "accounts"
            ]
          }
        ]
      }
    },
    "/za/pb/v1/accounts/{accountId}/balance": {
      "get": {
        "summary": "Get Account Balance",
        "description": "Obtain a specified account's balance.",
        "operationId": "balance",
        "tags": [
          "Account information"
        ],
        "security": [
          {
            "Oauth2": [
              "balances"
            ]
          },
          {
            "Oauth2-Sandbox": [
              "balances"
            ]
          }
        ]
      }
    },
    "/za/pb/v1/accounts/{accountId}/transactions": {
      "get": {
        "summary": "Get Account Transactions",
        "description": "Obtain a specified account's transactions.",
        "tags": [
          "Account information"
        ],
        "operationId": "accountsTransactions",
        "security": [
          {
            "Oauth2": [
              "transactions"
            ]
          },
          {
            "Oauth2-Sandbox": [
              "transactions"
            ]
          }
        ]
      }
    },
    "/za/pb/v1/accounts/transfermultiple": {
      "post": {
        "summary": "Transfer Multiple (TO BE DEPRECATED)",
        "description": "Transfer funds to one or multiple accounts.",
        "tags": [
          "Inter account transfers"
        ],
        "operationId": "transfer",
        "security": [
          {
            "Oauth2": [
              "transfers"
            ]
          },
          {
            "Oauth2-Sandbox": [
              "transfers"
            ]
          }
        ],
        "deprecated": true
      }
    },
    "/za/pb/v1/accounts/{accountId}/transfermultiple": {
      "post": {
        "summary": "Transfer Multiple v2",
        "description": "Transfer funds to one or multiple accounts.",
        "tags": [
          "Inter account transfers"
        ],
        "operationId": "transferv2",
        "security": [
          {
            "Oauth2": [
              "transfers"
            ]
          },
          {
            "Oauth2-Sandbox": [
              "transfers"
            ]
          }
        ]
      }
    },
    "/za/pb/v1/accounts/{accountId}/paymultiple": {
      "post": {
        "summary": "Pay Multiple",
        "description": "Pay funds to one or multiple beneficiaries. \n\n- Size limit of 50 payments per request.",
        "tags": [
          "Beneficiaries and Beneficiary payments"
        ],
        "operationId": "payBeneficiary",
        "security": [
          {
            "Oauth2": [
              "beneficiarypayments"
            ]
          },
          {
            "Oauth2-Sandbox": [
              "beneficiarypayments"
            ]
          }
        ]
      }
    },
    "/za/pb/v1/accounts/beneficiaries": {
      "get": {
        "summary": "Get Beneficiaries",
        "description": "List of beneficiaries linked to the profile",
        "tags": [
          "Beneficiaries and Beneficiary payments"
        ],
        "operationId": "beneficiaries",
        "security": [
          {
            "Oauth2": [
              "beneficiarypayments"
            ]
          },
          {
            "Oauth2-Sandbox": [
              "beneficiarypayments"
            ]
          }
        ]
      }
    },
    "/za/pb/v1/accounts/beneficiarycategories": {
      "get": {
        "summary": "Get Beneficiary Categories",
        "description": "List all the beneficiary categories available.",
        "operationId": "beneficiaryCategories",
        "tags": [
          "Beneficiaries and Beneficiary payments"
        ],
        "security": [
          {
            "Oauth2": [
              "beneficiarypayments"
            ]
          },
          {
            "Oauth2-Sandbox": [
              "beneficiarypayments"
            ]
          }
        ]
      }
    },
    "/za/pb/v1/profiles": {
      "get": {
        "summary": "Get Profiles",
        "description": "List all the profiles consented to.",
        "operationId": "profiles",
        "tags": [
          "Account information"
        ],
        "security": [
          {
            "Oauth2": [
              "accounts"
            ]
          },
          {
            "Oauth2-Sandbox": [
              "accounts"
            ]
          }
        ]
      }
    },
    "/za/pb/v1/profiles/{profileid}/accounts": {
      "get": {
        "summary": "Get Profile Accounts",
        "description": "List all the accounts for the profile specified.",
        "operationId": "profileaccounts",
        "tags": [
          "Account information"
        ],
        "security": [
          {
            "Oauth2": [
              "accounts"
            ]
          },
          {
            "Oauth2-Sandbox": [
              "accounts"
            ]
          }
        ]
      }
    },
    "/za/pb/v1/profiles/{profileid}/accounts/{accountid}/authorisationsetupdetails": {
      "get": {
        "summary": "Get Authorisation Setup Details",
        "description": "List the authorisation setup details for the specified profile and accounts.",
        "operationId": "authorisationsetupdetails",
        "tags": [
          "Account information"
        ],
        "security": [
          {
            "Oauth2": [
              "accounts"
            ]
          },
          {
            "Oauth2-Sandbox": [
              "accounts"
            ]
          }
        ]
      }
    },
    "/za/pb/v1/profiles/{profileid}/accounts/{accountid}/beneficiaries": {
      "get": {
        "summary": "Get Profile Beneficiaries",
        "description": "List all the beneficiaries available for the profile and account specified.",
        "operationId": "profilebenefiaries",
        "tags": [
          "Account information"
        ],
        "security": [
          {
            "Oauth2": [
              "accounts"
            ]
          },
          {
            "Oauth2-Sandbox": [
              "accounts"
            ]
          }
        ]
      }
    },
    "/za/pb/v1/accounts/{accountId}/documents": {
      "get": {
        "summary": "Get Documents",
        "description": "List all the documents available.",
        "operationId": "documents",
        "tags": [
          "Documents"
        ],
        "security": [
          {
            "Oauth2": [
              "documents.statements",
              "documents.taxcertificates"
            ]
          },
          {
            "Oauth2-Sandbox": [
              "documents.statements",
              "documents.taxcertificates"
            ]
          }
        ]
      }
    },
    "/za/pb/v1/accounts/{accountId}/document/{documentType}/{documentDate}": {
      "get": {
        "summary": "Get Document",
        "description": "Retrieve the document specified.",
        "operationId": "document",
        "tags": [
          "Documents"
        ],
        "security": [
          {
            "Oauth2": [
              "documents.statements",
              "documents.taxcertificates"
            ]
          },
          {
            "Oauth2-Sandbox": [
              "documents.statements",
              "documents.taxcertificates"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Oauth2": {
        "description": "The authentication flow complies to standard Oauth2 protocol but also requires an.<br>  **x-api-key** as an additional header. <br>Also remember to include **grant_type: client_credentials** (x-www-form-urlencoded) in the body of the request",
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://openapi.investec.com/identity/v2/oauth2/token",
            "x-api-key": "dWJHTHUxY1MzUnRjV3NzN29pWkpjNUZEbjhQaHhYUUw6N0YwRkNEQzgzQUE5MzdDQkNDMzhCMkU4ODQ2OUI1NzQ2MTQ1NTlENzgzQjRCMDhFRDBGMTY5NzQ5ODQzQjk1Qg==",
            "scopes": {
              "accounts": "Account information",
              "balances": "Account balance information",
              "transactions ": "Transaction history",
              "transfers": "Inter account transfer",
              "beneficiarypayments": "Beneficiary payments",
              "documents.statements": "Statements retrieval",
              "documents.taxcertificates": "Tax certificates retrieval"
            }
          }
        }
      },
      "Oauth2-Sandbox": {
        "description": "The authentication flow complies to standard Oauth2 protocol but also requires an.<br>  **x-api-key** as an additional header. <br>Also remember to include **grant_type: client_credentials** (x-www-form-urlencoded) in the body of the request \n## Sandbox\nThe sandbox environment allows you to test all personal Private Banking endpoints with mock data. All actions are immutable and can be run multiple times.\n\nTo use the sandbox environment simply use the base url `https:[...]",
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://openapisandbox.investec.com/identity/v2/oauth2/token",
            "scopes": {
              "accounts": "Account information",
              "balances": "Account balance information",
              "transactions ": "Transaction history",
              "transfers": "Inter account transfer",
              "beneficiarypayments": "Beneficiary payments"
            }
          }
        }
      }
    }
  },
  "security": []
}